function rcnn_fg_cache_features(config, chunk)

% -------------------- CONFIG --------------------
net_file     = './data/caffe_nets/finetune_voc_2007_trainval_iter_70k';
cache_name   = sprintf('%s_cache', config.domain);
crop_mode    = 'warp';
crop_padding = 16;
% ------------------------------------------------

imdb_train = imdb_from_fg_domain(config, 'train');
imdb_test  = imdb_from_fg_domain(config, 'test');

caffe('set_device', config.gpu_num);

switch chunk
  case 'train_1'
    start_at = ceil(0*length(imdb_train.image_ids)/2)+1;
    end_at   = ceil(1*length(imdb_train.image_ids)/2);
    rcnn_cache_pool5_features(imdb_train, ...
        'start', start_at, 'end', end_at, ...
        'crop_mode', crop_mode, ...
        'crop_padding', crop_padding, ...
        'net_file', net_file, ...
        'cache_name', cache_name);
  case 'train_2'
    start_at = ceil(1*length(imdb_train.image_ids)/2)+1;
    end_at   = ceil(2*length(imdb_train.image_ids)/2);
    rcnn_cache_pool5_features(imdb_train, ...
        'start', start_at, 'end', end_at, ...
        'crop_mode', crop_mode, ...
        'crop_padding', crop_padding, ...
        'net_file', net_file, ...
        'cache_name', cache_name);
  case 'test_1'
    start_at = ceil(0*length(imdb_test.image_ids)/2)+1;
    end_at   = ceil(1*length(imdb_test.image_ids)/2);
    rcnn_cache_pool5_features(imdb_test, ...
        'start', start_at, 'end', end_at, ...
        'crop_mode', crop_mode, ...
        'crop_padding', crop_padding, ...
        'net_file', net_file, ...
        'cache_name', cache_name);
  case 'test_2'
    start_at = ceil(1*length(imdb_test.image_ids)/2)+1;
    end_at   = ceil(2*length(imdb_test.image_ids)/2);
    rcnn_cache_pool5_features(imdb_test, ...
        'start', start_at, 'end', end_at, ...
        'crop_mode', crop_mode, ...
        'crop_padding', crop_padding, ...
        'net_file', net_file, ...
        'cache_name', cache_name);
end
